day_night: true
theme_day: minimal
theme: minimal
marketing:
  seo:
    site_type: Educational
    local_business_type: ''
    org_name: 'THL'
    description: 'thl'
    twitter: 'thl'
  analytics:
    google_analytics: ''
  verification:
    google: ''
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true
footer:
  copyright:
    notice: 'Â©2024 Md Tousif Hasan Lavlu | Last update on November, 2024'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us
features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - latex
      - python
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/thlavlu/thlavlu.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
publications:
  date_format: January 2006
  citation_style: apa